### ISSUE TITLE
StatusField not inserting values into database

### ISSUE THREAD

**Issue by fgs-dbudwin** [jazzband/django-model-utils#411]
## Problem

I have a very simple model in a Django 3.0.2 project that looks like the following:

```
from django.db import models

from model_utils import Choices
from model_utils.fields import StatusField

class MyStatus(models.Model):
    STATUS = Choices("A", "B", "C")

    name = StatusField()
```

After I run `makemigrations` I end up with the following:

```
# Generated by Django 3.0.2 on 2020-01-17 19:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', model_utils.fields.StatusField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], default='A', max_length=100, no_check_for_status=True)),
            ],
        ),
    ]
```
Finally, I run `migrate` which runs without problems.  However, when I inspect the table I just created in my SQLite database, my `example_mystatus` table is empty, just showing two columns: `id` and `name`.  I was expecting to see `A`, `B`, and `C` in my table as pre-populated values.

## Environment

- Django Model Utils version: 4.0.0
- Django version: 3.0.2
- Python version: 3.7.3
- Other libraries used, if any: N/A

## Code examples

See my example above.

**Comment by mattseymour** [comment]
@fgs-dbudwin the StatusField provides validations against the values which are saved into your `MyStatus` model; it does not populate the given model with values found in `STATUS`.

For example the below will validate and save the value into the MyStatus table as a new Record:
```
s = MyStatus(name='A')
s.save()
```

But if you had a "bad" status value (`name`), then you would expect to see a validation error being raised on save.
```
bad = MyStatus(name='BAD_STATUS')
bad.save()
```

If you want to keep the values of `STATUS` in the database you might want to look at using a ForeignKey lookup of the values instead of a status field.
